# Generated by Django 2.2.3 on 2019-07-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='region',
            name='cities',
            field=models.ManyToManyField(blank=True, to='main.City'),
        ),
    ]
